server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyanbin/springcloud2020.git
          ####搜索目录
          search-paths:
            - springcloud-config
      ###读取的分支
      label: master





eureka:
  client:
    service-url:
      #      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'