
server:
  port: 8002

eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径可以显示ip
  client:
    #表示自己注册到eureka
    register-with-eureka: true
    #入住到 eureka server, 集群为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/，http://eureka7003.com:7003/eureka/
      #eureka server 地址

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      kill-when-socket-read-timeout: false
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.springcloud.dao

#debug: true
#它一般对应我们的实体类所在的包，这个时候会自动取对应包中不包括包名的简单类名作为包括包名的别名。多个package之间可以用逗号或者分号等来进行分隔（value的值一定要是包的全）


